import Header from '@/components/layout/Header'
import './globals.css'
import { Roboto } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import { AppProvider } from '@/components/AppContext'

const roboto = Roboto({ subsets: ['latin']  , weight :['400' , '500' , '700']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className='max-w-4xl border mx-auto py-3 px-4 '>
          <AppProvider>
            <Header />
            {children}
          </AppProvider>
        </main>
        </body>
    </html>
  )
}
